services:
  link-shortener-api:
    image: link-shortener-api
    container_name: link-shortener-api
    build:
      context: src
      dockerfile: Presentation/LinkShortener.API/Dockerfile
    ports:
      - "8080:5001"
    networks:
      - link-shortener-network
    depends_on:
      - link-shortener-db
  
  link-shortener-db:
    image: mysql:latest
    container_name: link-shortener-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apiuserpassword
    networks:
      - link-shortener-network
    
networks:
  link-shortener-network:
    driver: bridge