// <auto-generated />
using System;
using LinkShortener.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkShortener.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250208175208_AddSomeUrlsMigration")]
    partial class AddSomeUrlsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LinkShortener.Domain.Entities.Url", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Urls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08dd4867-6777-4aef-8bb3-1d7219e41d67"),
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 7, 17, 38, 30, 0, DateTimeKind.Unspecified),
                            LongUrl = "https://vk.com",
                            ShortUrl = "1odc1dvGs"
                        },
                        new
                        {
                            Id = new Guid("08dd4867-6777-4aef-8bb3-1d1423e41d67"),
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 7, 21, 11, 59, 0, DateTimeKind.Unspecified),
                            LongUrl = "https://www.w3schools.com",
                            ShortUrl = "iJyKHaMAR"
                        },
                        new
                        {
                            Id = new Guid("08dd4867-8342-4d03-8b46-c95f4eebaac3"),
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 8, 9, 5, 12, 0, DateTimeKind.Unspecified),
                            LongUrl = "http://localhost:8080/swagger/index.html",
                            ShortUrl = "LDWQkfKhu"
                        },
                        new
                        {
                            Id = new Guid("08dd4867-944f-4e16-8631-f7a15d60a0f6"),
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 8, 11, 12, 42, 0, DateTimeKind.Unspecified),
                            LongUrl = "https://metanit.com",
                            ShortUrl = "XeWrGkd0S"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
